name: Metrics
on:
  # 毎日日本時間の深夜に自動実行
  schedule: [{cron: "0 15 * * *"}]
  # 手動でも実行できるようにする（テスト用）
  workflow_dispatch:
  # メインのREADMEを更新した時にも実行
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # 先ほど金庫に入れた名前
          token: ${{ secrets.METRICS_TOKEN }}
          user: komatsu-3d
          template: classic
          base: header, activity, community, repositories, metadata
          # プライベートリポジトリの活動も集計対象に含める
          config_display: large
          config_timezone: Asia/Tokyo
          # 小松さんが欲しかった「ゴリゴリの推移」グラフを表示
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
