name: MLB Update
on:
  workflow_dispatch: # 手動で動かすためのボタン
  schedule:
    - cron: '0 0 * * *' # 毎日自動更新
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ←ここが「読み書き許可」の生命線です！
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install requests
      - run: python update_mlb.py
      - name: Save to README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update Ohtani" || exit 0
          git push origin main
